# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: SigmaSistemi.Giant2
PackageVersion: 2.5.1
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ProductCode: '{29958FA0-F6C1-4A1B-A787-88E361AF40F5}'
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/SigmaSistemi/giant2/releases/download/v2.5.1/Giant2.5_setup.msi
  InstallerSha256: A49FE737B9550760F68D91D84B3FD92481DC4D9865384CDB225A00F0F146D9CF
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2026-09-28
